general:
  data_path: ../../input/data/
  model_name: digit82/kobart-summarization
  output_dir: ./
inference:
  batch_size: 32
  ckt_path: model ckt path
  early_stopping: true
  generate_max_length: 65
  no_repeat_ngram_size: 3
  num_beams: 6
  remove_tokens:
  - <usr>
  - <s>
  - </s>
  - <pad>
  result_path: ./prediction/
tokenizer:
  bos_token: <s>
  decoder_max_len: 91
  encoder_max_len: 470
  eos_token: </s>
  special_tokens:
  - '#Person1#'
  - '#Person2#'
  - '#Person3#'
  - '#PhoneNumber#'
  - '#Address#'
  - '#PassportNumber#'
training:
  do_eval: true
  do_train: true
  early_stopping_patience: 10
  early_stopping_threshold: 0.0010504327073920748
  evaluation_strategy: epoch
  fp16: true
  generation_max_length: 90
  gradient_accumulation_steps: 4
  learning_rate: 0.00034617979350923657
  load_best_model_at_end: true
  logging_dir: ./logs
  logging_strategy: epoch
  lr_scheduler_type: cosine
  num_train_epochs: 8
  optim: adamw_torch_fused
  overwrite_output_dir: true
  per_device_eval_batch_size: 32
  per_device_train_batch_size: 8
  predict_with_generate: true
  report_to: wandb
  save_strategy: epoch
  save_total_limit: 5
  seed: 972707
  use_early_stopping: false
  warmup_ratio: 0.0924713094045585
  weight_decay: 0.01966044666050655
wandb:
  entity: moonstalker9010-none
  name: jhryu_baseline_exp
  project: NLP
